import React from 'react';
import { 
  LayoutDashboard, 
  Wallet, 
  ArrowRightLeft, 
  CreditCard, 
  TrendingUp, 
  TrendingDown, 
  Settings, 
  Plus, 
  PieChart, 
  FolderTree,
  DollarSign,
  Calendar,
  Target,
  LogOut,
  Moon,
  Sun,
  Briefcase,
  User,
  Tags,
  Menu,
  X,
  Building,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Upload
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Wallet,
  Transfer: ArrowRightLeft,
  Subscription: CreditCard,
  Income: TrendingUp,
  Expense: TrendingDown,
  Settings,
  Plus,
  Chart: PieChart,
  Accounts: FolderTree,
  Dollar: DollarSign,
  Calendar,
  Target,
  LogOut,
  Moon,
  Sun,
  Business: Briefcase,
  Personal: User,
  Category: Tags,
  Menu,
  Close: X,
  Building,
  Check: CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Upload
};